package com.personalAssist.SDP.enums;

public enum TypeEnum {

	HOUSE_CLEANING,
    LAWN_MOWING_AND_GARDENING,
    END_OF_LEASE_CLEANING,
    CAR_WASHING_AND_DETAILING,
    CHILDCARE_OR_BABYSITTING,
    AGED_CARE_OR_HOME_ASSISTANCE,
    PET_SITTING_OR_DOG_WALKING,
    LAUNDRY_AND_IRONING,
    FURNITURE_ASSEMBLY
}
